/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-12-11 12:47:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home.app.producao;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.Ingrediente;

public final class ingrediente_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("model.Ingrediente");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Ingrediente Form</title>\n");
      out.write("        <style>\n");
      out.write("            body {\n");
      out.write("                font-family: Arial, sans-serif;\n");
      out.write("                background-color: #f4f4f4;\n");
      out.write("                color: #333;\n");
      out.write("                margin: 0;\n");
      out.write("                padding: 20px;\n");
      out.write("            }\n");
      out.write("            .form-container {\n");
      out.write("                width: 50%;\n");
      out.write("                margin: 30px auto;\n");
      out.write("                background-color: #fff;\n");
      out.write("                padding: 30px;\n");
      out.write("                border-radius: 8px;\n");
      out.write("                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n");
      out.write("            }\n");
      out.write("            h1 {\n");
      out.write("                text-align: center;\n");
      out.write("                color: #e74c3c;\n");
      out.write("                margin-bottom: 25px;\n");
      out.write("            }\n");
      out.write("            label {\n");
      out.write("                display: block;\n");
      out.write("                margin-top: 15px;\n");
      out.write("                font-weight: bold;\n");
      out.write("                color: #333;\n");
      out.write("            }\n");
      out.write("            input[type=\"text\"], input[type=\"email\"], input[type=\"tel\"], input[type=\"password\"], input[type=\"number\"], select, textarea {\n");
      out.write("                width: 100%;\n");
      out.write("                padding: 10px;\n");
      out.write("                margin-top: 5px;\n");
      out.write("                border: 1px solid #ccc;\n");
      out.write("                border-radius: 4px;\n");
      out.write("                box-sizing: border-box;\n");
      out.write("                font-size: 16px;\n");
      out.write("            }\n");
      out.write("            input[type=\"submit\"] {\n");
      out.write("                background-color: #27ae60;\n");
      out.write("                color: white;\n");
      out.write("                padding: 12px 20px;\n");
      out.write("                border: none;\n");
      out.write("                border-radius: 4px;\n");
      out.write("                cursor: pointer;\n");
      out.write("                width: 100%;\n");
      out.write("                margin-top: 30px;\n");
      out.write("                font-size: 18px;\n");
      out.write("                transition: background-color 0.3s;\n");
      out.write("            }\n");
      out.write("            input[type=\"submit\"]:hover {\n");
      out.write("                background-color: #229954;\n");
      out.write("            }\n");
      out.write("            .btn-voltar {\n");
      out.write("                display: block;\n");
      out.write("                width: 100%;\n");
      out.write("                text-align: center;\n");
      out.write("                margin-top: 20px;\n");
      out.write("                padding: 8px;\n");
      out.write("                background-color: #3498db;\n");
      out.write("                color: white;\n");
      out.write("                text-decoration: none;\n");
      out.write("                border-radius: 4px;\n");
      out.write("            }\n");
      out.write("            .btn-voltar:hover {\n");
      out.write("                background-color: #2980b9;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");

            Ingrediente ing = null;
            String action = request.getParameter("action");
            
            if (action == null || action.isEmpty()) {
                action = "create";
            } else if (action.equals("update")) {
                int id = Integer.valueOf(request.getParameter("id"));
                ing = new Ingrediente();
                ing.setIdIngrediente(id);
                ing.load();
            }
        
      out.write("\n");
      out.write("        <div class=\"form-container\">\n");
      out.write("            <h1>");
      out.print( action.equals("create") ? "Adicionar Novo Ingrediente" : "Alterar Ingrediente" );
      out.write("</h1>\n");
      out.write("            <form action=\"");
      out.print( request.getContextPath());
      out.write("/home?action=");
      out.print( action);
      out.write("&task=ingredientes\" method=\"post\">\n");
      out.write("                \n");
      out.write("                <label for=\"id_ingrediente\">ID:</label>\n");
      out.write("                <input type=\"text\" id=\"id_ingrediente\" name=\"id_ingrediente\" pattern=\"\\d+\" title=\"Apenas dígitos\" value=\"");
      out.print( (ing != null) ? ing.getIdIngrediente() : "" );
      out.write('"');
      out.write(' ');
      out.print( (ing != null) ? "readonly" : "");
      out.write(" required>\n");
      out.write("                \n");
      out.write("                <label for=\"nome\">Nome do Ingrediente:</label>\n");
      out.write("                <input type=\"text\" id=\"nome\" name=\"nome\" value=\"");
      out.print( (ing != null) ? ing.getNome() : "");
      out.write("\" required>\n");
      out.write("                \n");
      out.write("                <label for=\"quantidade_estoque\">Quantidade em Estoque:</label>\n");
      out.write("                <input type=\"number\" id=\"quantidade_estoque\" name=\"quantidade_estoque\" min=\"0\" title=\"Apenas números inteiros positivos\" value=\"");
      out.print( (ing != null) ? ing.getQuantidadeEstoque() : "");
      out.write("\" required>\n");
      out.write("                \n");
      out.write("                <label for=\"unidade_medida\">Unidade de Medida:</label>\n");
      out.write("                <select id=\"unidade_medida\" name=\"unidade_medida\" required>\n");
      out.write("                    <option value=\"kg\" ");
      out.print( (ing != null && ing.getUnidadeMedida().equals("kg")) ? "selected" : "" );
      out.write(">Kilograma (kg)</option>\n");
      out.write("                    <option value=\"g\" ");
      out.print( (ing != null && ing.getUnidadeMedida().equals("g")) ? "selected" : "" );
      out.write(">Grama (g)</option>\n");
      out.write("                    <option value=\"L\" ");
      out.print( (ing != null && ing.getUnidadeMedida().equals("L")) ? "selected" : "" );
      out.write(">Litro (L)</option>\n");
      out.write("                    <option value=\"un\" ");
      out.print( (ing != null && ing.getUnidadeMedida().equals("un")) ? "selected" : "" );
      out.write(">Unidade (un)</option>\n");
      out.write("                </select>\n");
      out.write("                \n");
      out.write("                <input type=\"submit\" value=\"Salvar Ingrediente\">\n");
      out.write("            </form>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath());
      out.write("/home/app/producao/ingredientes.jsp\" class=\"btn-voltar\">Voltar</a>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
