/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-12-11 12:46:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home.app;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.HttpSession;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/home/app/modulos.jsp", Long.valueOf(1765457119939L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("jakarta.servlet.http.HttpSession");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Menu Principal - PizzaManager</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Módulos - PizzaManager</title>\n");
      out.write("        <style>\n");
      out.write("            body {\n");
      out.write("                font-family: Arial, sans-serif;\n");
      out.write("                background-color: #f4f4f4;\n");
      out.write("                color: #333;\n");
      out.write("                margin: 0;\n");
      out.write("                padding: 0;\n");
      out.write("            }\n");
      out.write("            .header-info {\n");
      out.write("                background-color: #c0392b;\n");
      out.write("                color: white;\n");
      out.write("                padding: 15px 30px;\n");
      out.write("                display: flex;\n");
      out.write("                justify-content: space-between;\n");
      out.write("                align-items: center;\n");
      out.write("                box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);\n");
      out.write("            }\n");
      out.write("            .header-info h1 {\n");
      out.write("                margin: 0;\n");
      out.write("                font-size: 1.8rem;\n");
      out.write("            }\n");
      out.write("            .user-details {\n");
      out.write("                text-align: right;\n");
      out.write("            }\n");
      out.write("            .user-details span {\n");
      out.write("                display: block;\n");
      out.write("                font-weight: bold;\n");
      out.write("            }\n");
      out.write("            nav {\n");
      out.write("                background-color: #e74c3c;\n");
      out.write("                padding: 0 30px;\n");
      out.write("            }\n");
      out.write("            nav ul {\n");
      out.write("                list-style: none;\n");
      out.write("                padding: 0;\n");
      out.write("                margin: 0;\n");
      out.write("                display: flex;\n");
      out.write("                justify-content: flex-start;\n");
      out.write("                align-items: center;\n");
      out.write("            }\n");
      out.write("            nav ul li {\n");
      out.write("                margin-right: 20px;\n");
      out.write("            }\n");
      out.write("            nav ul li a {\n");
      out.write("                color: white;\n");
      out.write("                text-decoration: none;\n");
      out.write("                padding: 10px 15px;\n");
      out.write("                display: block;\n");
      out.write("                border-radius: 4px;\n");
      out.write("                transition: background-color 0.3s;\n");
      out.write("                font-weight: 600;\n");
      out.write("            }\n");
      out.write("            nav ul li a:hover {\n");
      out.write("                background-color: #c0392b;\n");
      out.write("            }\n");
      out.write("            .logout-link {\n");
      out.write("                margin-left: auto;\n");
      out.write("                background-color: #34495e;\n");
      out.write("                border-radius: 0;\n");
      out.write("            }\n");
      out.write("            .logout-link a {\n");
      out.write("                padding: 10px 20px;\n");
      out.write("                font-size: 0.95rem;\n");
      out.write("                background-color: transparent;\n");
      out.write("            }\n");
      out.write("            .logout-link a:hover {\n");
      out.write("                background-color: #2c3e50;\n");
      out.write("            }\n");
      out.write("            .content {\n");
      out.write("                padding: 30px;\n");
      out.write("                text-align: center;\n");
      out.write("            }\n");
      out.write("            .welcome-box {\n");
      out.write("                background: white;\n");
      out.write("                padding: 30px;\n");
      out.write("                border-radius: 8px;\n");
      out.write("                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n");
      out.write("                margin-top: 20px;\n");
      out.write("            }\n");
      out.write("            .welcome-box h2 {\n");
      out.write("                color: #2c3e50;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");

            String usuarioNome = (String) session.getAttribute("usuario_nome");
            String cargo = (String) session.getAttribute("cargo");

            if (usuarioNome == null || cargo == null) {
                response.sendRedirect(request.getContextPath() + "/home/login.jsp");
                return;
            }

            boolean isGerente = "Gerente".equals(cargo);
            boolean isPizzaiolo = "Pizzaiolo".equals(cargo);
            boolean isAtendente = "Atendente".equals(cargo);
        
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"header-info\">\n");
      out.write("            <h1>PizzaManager - Sistema</h1>\n");
      out.write("            <div class=\"user-details\">\n");
      out.write("                <span>Bem-vindo(a), ");
      out.print( usuarioNome);
      out.write("</span>\n");
      out.write("                <small>(");
      out.print( cargo);
      out.write(")</small>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <nav>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/home/app/menu.jsp\">Início / Menu</a></li>\n");
      out.write("\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/home/app/geral/clientes.jsp\">Clientes</a></li>\n");
      out.write("\n");
      out.write("                ");
 if (isGerente || isAtendente) {
      out.write("\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/home/app/vendas/produtos.jsp\">Produtos/Sabores</a></li>\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/home/app/vendas/pedidos.jsp\">Pedidos</a></li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                ");
 if (isGerente || isPizzaiolo) {
      out.write("\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/home/app/producao/ingredientes.jsp\">Estoque/Ingredientes</a></li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                ");
 if (isGerente) {
      out.write("\n");
      out.write("                <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/home/app/adm/funcionarios.jsp\">Funcionários</a></li>\n");
      out.write("                ");
 }
      out.write("\n");
      out.write("\n");
      out.write("                <li class=\"logout-link\"><a href=\"");
      out.print( request.getContextPath());
      out.write("/home?task=logout\">Sair (Logout)</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </nav>\n");
      out.write("\n");
      out.write("        <div class=\"content\">\n");
      out.write("            <div class=\"welcome-box\">\n");
      out.write("                <h2>Gerenciamento de Pizzaria</h2>\n");
      out.write("                <p>Use o menu superior para acessar os módulos permitidos ao seu cargo de <strong>");
      out.print( cargo );
      out.write("</strong>.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("        \n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
