/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.44
 * Generated at: 2025-12-11 12:47:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home.app.vendas;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.Pedido;
import java.util.ArrayList;
import java.text.SimpleDateFormat;

public final class pedidos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("model.Pedido");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Pedidos - PizzaManager</title>\n");
      out.write("        <style>\n");
      out.write("            body {\n");
      out.write("                font-family: Arial, sans-serif;\n");
      out.write("                background-color: #f4f4f4;\n");
      out.write("                color: #333;\n");
      out.write("                margin: 0;\n");
      out.write("                padding: 20px;\n");
      out.write("            }\n");
      out.write("            .container {\n");
      out.write("                width: 90%;\n");
      out.write("                margin: 20px auto;\n");
      out.write("                background-color: #fff;\n");
      out.write("                padding: 20px;\n");
      out.write("                border-radius: 8px;\n");
      out.write("                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n");
      out.write("            }\n");
      out.write("            h1 {\n");
      out.write("                text-align: center;\n");
      out.write("                color: #e74c3c;\n");
      out.write("                margin-bottom: 20px;\n");
      out.write("            }\n");
      out.write("            table {\n");
      out.write("                width: 100%;\n");
      out.write("                border-collapse: collapse;\n");
      out.write("                margin: 20px 0;\n");
      out.write("            }\n");
      out.write("            th, td {\n");
      out.write("                padding: 12px 15px;\n");
      out.write("                text-align: left;\n");
      out.write("                border-bottom: 1px solid #ddd;\n");
      out.write("            }\n");
      out.write("            th {\n");
      out.write("                background-color: #c0392b;\n");
      out.write("                color: white;\n");
      out.write("                text-transform: uppercase;\n");
      out.write("            }\n");
      out.write("            tr:nth-child(even) {\n");
      out.write("                background-color: #f9f9f9;\n");
      out.write("            }\n");
      out.write("            tr:hover {\n");
      out.write("                background-color: #f1f1f1;\n");
      out.write("            }\n");
      out.write("            a {\n");
      out.write("                display: inline-block;\n");
      out.write("                padding: 6px 10px;\n");
      out.write("                margin: 2px;\n");
      out.write("                text-decoration: none;\n");
      out.write("                border-radius: 4px;\n");
      out.write("                font-size: 14px;\n");
      out.write("                transition: background-color 0.3s;\n");
      out.write("            }\n");
      out.write("            a:not(.link-excluir):not(.link-adicionar):not(.btn-voltar-menu) {\n");
      out.write("                background-color: #3498db;\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            a:not(.link-excluir):not(.link-adicionar):not(.btn-voltar-menu):hover {\n");
      out.write("                background-color: #2980b9;\n");
      out.write("            }\n");
      out.write("            .link-excluir {\n");
      out.write("                background-color: #e74c3c;\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .link-excluir:hover {\n");
      out.write("                background-color: #c0392b;\n");
      out.write("            }\n");
      out.write("            .link-adicionar {\n");
      out.write("                display: block;\n");
      out.write("                width: 150px;\n");
      out.write("                text-align: center;\n");
      out.write("                margin: 20px auto 0;\n");
      out.write("                padding: 10px;\n");
      out.write("                background-color: #27ae60;\n");
      out.write("                color: white;\n");
      out.write("                font-weight: bold;\n");
      out.write("            }\n");
      out.write("            .link-adicionar:hover {\n");
      out.write("                background-color: #229954;\n");
      out.write("            }\n");
      out.write("            .btn-voltar-menu {\n");
      out.write("                display: block;\n");
      out.write("                width: 250px;\n");
      out.write("                text-align: center;\n");
      out.write("                margin: 20px auto 10px;\n");
      out.write("                padding: 10px;\n");
      out.write("                background-color: #34495e; \n");
      out.write("                color: white;\n");
      out.write("                font-weight: bold;\n");
      out.write("                border-radius: 4px;\n");
      out.write("                text-decoration: none;\n");
      out.write("            }\n");
      out.write("            .btn-voltar-menu:hover {\n");
      out.write("                background-color: #2c3e50;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
 
            ArrayList<Pedido> dados = new Pedido().getAllTableEntities(); 
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        
      out.write("\n");
      out.write("        <h1>Pedidos</h1>\n");
      out.write("        \n");
      out.write("        <a href=\"");
      out.print( request.getContextPath());
      out.write("/home/app/menu.jsp\" class=\"btn-voltar-menu\">\n");
      out.write("            <-- Voltar ao Menu Principal\n");
      out.write("        </a>\n");
      out.write("        \n");
      out.write("        <div class=\"container\">\n");
      out.write("        <table>\n");
      out.write("            <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th>ID Pedido</th>\n");
      out.write("                    <th>Data/Hora</th>\n");
      out.write("                    <th>Valor Total</th>\n");
      out.write("                    <th>Status</th>\n");
      out.write("                    <th>ID Cliente</th>\n");
      out.write("                    <th>ID Funcionário</th>\n");
      out.write("                    <th>Ações</th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("                ");
 for(Pedido ped : dados) { 
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( ped.getIdPedido() );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( sdf.format(ped.getDtHora()) );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( String.format("R$ %,.2f", ped.getValorTotal()));
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( ped.getStatus());
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( ped.getIdCliente());
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( ped.getIdFuncionario());
      out.write("</td>\n");
      out.write("                    <td> \n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath());
      out.write("/home/app/vendas/pedido_form.jsp?action=update&id=");
      out.print( ped.getIdPedido() );
      out.write("\">Alterar</a>\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath());
      out.write("/home?action=delete&id=");
      out.print( ped.getIdPedido() );
      out.write("&task=pedidos\" onclick=\"return confirm('Deseja excluir Pedido ");
      out.print( ped.getIdPedido());
      out.write("?')\" class=\"link-excluir\" >Excluir</a>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                ");
 }
      out.write("\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("        </div>\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath());
      out.write("/home/app/vendas/pedido_form.jsp?action=create\" class=\"link-adicionar\">Adicionar Novo Pedido</a>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
